sudo: false # 使用容器进行编译，速度更快
dist: trusty # 编译的操作系统是 ubuntu trusty，目前还不支持 xenial 或更高版本
language: go # 表示 repo 是一个 go 项目
go: 1.10.x # 指定编译时的 go 版本号
git:
  submodules: false # 不运行 git submodules 命令
before_install: # 安装 makefile 需要的一些包，其实也可以放在 install 阶段，看个人喜好
- sudo apt-get update -qq
- sudo apt-get install -qq -y make
install: true # 跳过 install 阶段，因为我已经定义了 before_install。其实 go 项目是需要安装依赖的，只是我放到了下面的 make mycli 命令中做
script: make fmt && make # 先检查格式，然后编译

